/**
 * X-Matrix — 全局响应式状态定义
 * 包含所有 Alpine.js 响应式数据（不含方法）
 */
window.XMatrixState = {
        currentTab: 'home',
        sidebarCollapsed: window.innerWidth < 1024,
        proxyMode: localStorage.getItem('xmatrix_proxy_mode') || 'rule',
        systemProxy: false,
        tunMode: _safeJsonParse('xmatrix_tun_mode', false),
        coreState: { isRunning: false },
        configState: (() => {
          var cached = _safeJsonParse('xmatrix_config_state', {});
          return {
            localPort: cached.localPort || 2077,
            allowLan: cached.allowLan != null ? cached.allowLan : false,
            enableUdp: cached.enableUdp != null ? cached.enableUdp : true,
            sniffing: cached.sniffing != null ? cached.sniffing : true,
            sniffTypes: cached.sniffTypes || ['http', 'tls'],
            enableCustomDns: cached.enableCustomDns != null ? cached.enableCustomDns : false,
            remoteDns: cached.remoteDns || 'https+local://1.1.1.1/dns-query',
            localDns: cached.localDns || '223.5.5.5',
            directDns: cached.directDns || '',
            fakeIpRange: cached.fakeIpRange || '198.18.0.0/15',
            dnsRules: cached.dnsRules || [],
            enableFragment: cached.enableFragment != null ? cached.enableFragment : false,
            fragmentPackets: cached.fragmentPackets || 'tlshello',
            fragmentLength: cached.fragmentLength || '100-200',
            fragmentInterval: cached.fragmentInterval || '10-20',
            tunMtu: cached.tunMtu || 9000,
            tunStack: cached.tunStack || 'system',
            tunAutoRoute: cached.tunAutoRoute != null ? cached.tunAutoRoute : true,
            tunStrictRoute: cached.tunStrictRoute != null ? cached.tunStrictRoute : true,
            tunExcludeAddress: cached.tunExcludeAddress || '',
            tunExcludeApps: cached.tunExcludeApps || '',
            enableMux: cached.enableMux != null ? cached.enableMux : false,
            muxConcurrency: cached.muxConcurrency || 8,
            inboundAuth: cached.inboundAuth != null ? cached.inboundAuth : false,
            inboundUser: cached.inboundUser || '',
            inboundPass: cached.inboundPass || '',
            lanPort: cached.lanPort || 0,
            httpPort: cached.httpPort || 0,
            secondPort: cached.secondPort || 0,
            secondSocksEnabled: cached.secondSocksEnabled != null ? cached.secondSocksEnabled : false,
            tunIncludeApps: cached.tunIncludeApps || '',
            useSystemHosts: cached.useSystemHosts != null ? cached.useSystemHosts : true,
            strategy4proxy: cached.strategy4proxy || '',
            strategy4freedom: cached.strategy4freedom || '',
            tunIpv6: cached.tunIpv6 != null ? cached.tunIpv6 : false,
            muxXudpConcurrency: cached.muxXudpConcurrency || 8,
            muxXudpProxyUdp443: cached.muxXudpProxyUdp443 || 'reject'
          };
        })(),
        settingsState: {
          sysProxyMode: localStorage.getItem('xmatrix_sys_proxy_mode') || 'pac',
          hotkeyWindow: localStorage.getItem('xmatrix_hk_win') || 'ctrl+shift+x',
          hotkeyProxy: localStorage.getItem('xmatrix_hk_proxy') || 'ctrl+shift+s',
          autoStart: false,
          autoActivateNode: _safeJsonParse('xmatrix_auto_activate', false),
          silentStart: _safeJsonParse('xmatrix_silent_start', false),
          closeBehavior: localStorage.getItem('xmatrix_close_behavior') || 'quit',
          keepOlderDedup: _safeJsonParse('xmatrix_keep_older_dedup', true),
          delayTestUrl: localStorage.getItem('xmatrix_delay_test_url') || 'https://www.google.com/generate_204',
          downloadTestUrl: localStorage.getItem('xmatrix_download_test_url') || 'https://cachefly.cachefly.net/50mb.test',
          testTimeout: parseInt(localStorage.getItem('xmatrix_test_timeout') || '5000'),
          testConcurrency: parseInt(localStorage.getItem('xmatrix_test_concurrency') || '5'),
          theme: localStorage.getItem('xmatrix_theme') || 'system',
          trayLimit: parseInt(localStorage.getItem('xmatrix_tray_limit') || '100'),
          ipinfoToken: localStorage.getItem('xmatrix_ipinfo_token') || '',
          defFingerprint: localStorage.getItem('xmatrix_def_fingerprint') || '',
          defUserAgent: localStorage.getItem('xmatrix_def_user_agent') || '',
          proxyExceptions: localStorage.getItem('xmatrix_proxy_exceptions') || '',
          enableHwa: _safeJsonParse('xmatrix_enable_hwa', true),
          configPriority: localStorage.getItem('xmatrix_config_priority') || 'smart',
          coreTypeMap: _safeJsonParse('xmatrix_core_type_map', {}),
          preServiceEnabled: _safeJsonParse('xmatrix_pre_service_enabled', false),
          preServiceCore: localStorage.getItem('xmatrix_pre_service_core') || 'xray',
          connectionsAutoRefresh: _safeJsonParse('xmatrix_conn_auto_refresh', false),
          connectionsRefreshInterval: parseInt(localStorage.getItem('xmatrix_conn_refresh_interval') || '2'),
          autoDelayTestInterval: localStorage.getItem('xmatrix_auto_delay_test_interval') || '0',
          checkPrerelease: _safeJsonParse('xmatrix_check_prerelease', false),
          geoipUrl: localStorage.getItem('xmatrix_geoip_url') || '',
          geositeUrl: localStorage.getItem('xmatrix_geosite_url') || '',
          srsUrl: localStorage.getItem('xmatrix_srs_url') || ''
        },
        traffic: {
          upSpeed: '0.00 B/s',
          downSpeed: '0.00 B/s',
          upTotal: '0.00 B',
          downTotal: '0.00 B',
          connections: 0,
          memory: '0.0 MB',
          chartRange: 60,
          historyUp: [],
          historyDown: []
        },
        isActivatingNode: false,
        toasts: [],
        clipboardPrompt: { show: false, text: '' },
        qrModal: { show: false, uri: '' },
        lastClipboardText: '',
        showRouteList: false,
        coreTypes: [],
        get isDark() { return this.settingsState.theme === 'dark' || (this.settingsState.theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches); },
        get activeCoreType() { const c = (this.coreTypes || []).find(c => c.active); return c ? c.type : 'xray'; },
        wallpaperPath: localStorage.getItem('xmatrix_wallpaper') || '',
        glassOpacity: localStorage.getItem('xmatrix_glass_opacity') !== null ? parseInt(localStorage.getItem('xmatrix_glass_opacity')) : 60,
        displayOptions: _safeJsonParse('xmatrix_display', {showProtocol: true, showAddress: true, showDelay: true}),
        saveDisplayOptions() { localStorage.setItem('xmatrix_display', JSON.stringify(this.displayOptions)); },
        showToast(msg, type = 'info') {
          const id = Date.now() + Math.random();
          this.toasts.push({ id, msg, type });
          setTimeout(() => { this.toasts = this.toasts.filter(t => t.id !== id); }, 3000);
        }
};
